name: Deployment Rocket API

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Deploy Auth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install packages
        run: |
          sudo curl -o /usr/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x /usr/bin/jq
          pip3 install awscli
          npm install -g aws-cdk

      - name: Prepare
        run: |
          cd ./auth
          npm i
          
      - name: Deploy Prd
        if: github.ref == 'refs/heads/master'
        run: |
          npm run build
          cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_DEFAULT_REGION}
          cdk deploy '*' --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_NAME: rocket-auth
          SIGNIN_CALLBACK_URL: ${{ secrets.SIGNIN_CALLBACK_URL }}
          SIGNOUT_CALLBACK_URL: ${{ secrets.SIGNOUT_CALLBACK_URL }}
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
          GOOGLE_WEB_APP_SECRET: ${{ secrets.GOOGLE_WEB_APP_SECRET }}
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}

      - name: Deploy Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          npm run build
          cdk bootstrap aws://${AWS_ACCOUNT_ID}/${AWS_DEFAULT_REGION}
          cdk deploy '*' --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APP_NAME: rocket-auth-dev
          SIGNIN_CALLBACK_URL: ${{ secrets.SIGNIN_CALLBACK_URL_DEV }}
          SIGNOUT_CALLBACK_URL: ${{ secrets.SIGNOUT_CALLBACK_URL_DEV }}
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID_DEV }}
          GOOGLE_WEB_APP_SECRET: ${{ secrets.GOOGLE_WEB_APP_SECRET_DEV }}
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID_DEV }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET_DEV }}
 